name: Build and Deploy
on: [push, pull_request]

concurrency:
  group: ${{ github.head_ref }}-docs
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
          .github/workflows/dependencies/documentation.sh
          echo "Installing python packages for docs..."
          pip3 install sphinx sphinx_rtd_theme breathe

      - name: Install and Build
        run: |
          cd Docs/sphinx_documentation
          echo "Build the Sphinx documentation for incflo."
          make html

      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'AMReX-Fluids/incflo' && github.ref == 'refs/heads/development'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages # The branch the action should deploy to.
          folder: Docs/sphinx_documentation/build/html # The folder the action should deploy.
          target-folder: docs_html # The folder the action should deploy to.
          clean: false # Do not remove existing files from the deploy target.
