---
name: HIP

on:
  push:
  pull_request:
  schedule:
    - cron: "13 8 * * *"

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-HIP
  cancel-in-progress: true

jobs:
  hip_no_eb_3d:
    if: ${{ github.repository == 'AMReX-Fluids/incflo' || github.event_name != 'schedule' }}
    name: HIP NO EB 3D
    runs-on: ubuntu-20.04
    env: {CXXFLAGS: "-Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -Wextra-semi -Wunreachable-code -Wnon-virtual-dtor -Wno-deprecated-declarations -Wno-gnu-zero-variadic-macro-arguments"}
    steps:
    - name: Checkout incflo
      uses: actions/checkout@v3
      with:
        path: incflo
    - name: Checkout AMReX-Hydro
      uses: actions/checkout@v3
      with:
        repository: AMReX-Fluids/AMReX-Hydro
        path: AMReX-Hydro
    - name: Checkout AMReX
      uses: actions/checkout@v3
      with:
        repository: AMReX-Codes/amrex
        path: amrex
    - name: Set Up Cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/ccache
        key: ccache-${{ github.workflow }}-${{ github.job }}-git-${{ github.sha }}
        restore-keys: |
             ccache-${{ github.workflow }}-${{ github.job }}-git-
    - name: Load Dependencies
      run: |
        amrex/.github/workflows/dependencies/dependencies_hip.sh
        amrex/.github/workflows/dependencies/dependencies_ccache.sh
    - name: Build
      run: |
        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=10
        export CCACHE_MAXSIZE=200M
        ccache -z

        source /etc/profile.d/rocm.sh
        hipcc --version
        which clang
        which clang++

        cd incflo
        mkdir build
        cd build
        cmake ..                                                     \
           -DINCFLO_DIM=3                                            \
           -DINCFLO_MPI=OFF                                          \
           -DINCFLO_OMP=OFF                                          \
           -DINCFLO_EB=OFF                                           \
           -DINCFLO_HIP=ON                                           \
           -DAMReX_AMD_ARCH=gfx90a                                   \
           -DAMREX_HOME=${{ github.workspace }}/amrex                \
           -DAMREX_HYDRO_HOME=${{ github.workspace }}/AMReX-Hydro    \
           -DCMAKE_VERBOSE_MAKEFILE=ON                               \
           -DCMAKE_C_COMPILER=$(which clang)                         \
           -DCMAKE_CXX_COMPILER=$(which clang++)                     \
           -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        make -j 2

        ccache -s
        du -hs ~/.cache/ccache

  save_pr_number:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > pr_number.txt
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr_number.txt
          retention-days: 1
